### ISSUE TITLE
Database Strukture cant be downloaded from your domain. 

### ISSUE THREAD

**Issue by magic-space** [MarcelKaemper/HackergameV2#10]
Hey woher bekomme ich die datenbank?

**Comment by Jejemion** [comment]
Where structure data?

**Comment by wumix** [comment]
I can't install the game.

How to install this game.



Jejemion <notifications@github.com> schrieb am Di., 8. Sept. 2020, 12:27:

**Comment by Jejemion** [comment]
![Screenshot_2020-09-13-15-52-34](https://user-images.githubusercontent.com/64363636/93014189-3094fc00-f5d9-11ea-9545-363b44120a2a.png)

Look,  i can create a database for this game

**Comment by magic-space** [comment]
Okay I looking for the structure.zip of this game.

**Comment by MarcelKaemper** [comment]
Hey there.

We appreciate that you're interested in our project.

I updated the download link in the README.md.

You can download the DB_Structure SQL script [here](https://marcelkaemper.dev/db_structure.sql)

**Comment by MarcelKaemper** [comment]
Does it work out for you or are you having any trouble?

Feel free to reply in case you're experiencing any issues.

**Comment by MarcelKaemper** [comment]
[This](https://marcelkaemper.dev/db_structure_09_20.sql) is the new version with enhanced compatibility for new MySQL versions.

I will close this issue now, you may reopen it if you have any further questions regarding the DB Structure.
