### ISSUE TITLE
Hey is not an issue

### ISSUE THREAD

**Issue by wumix** [MarcelKaemper/HackergameV2#2]
You have any Demo of this script

**Comment by MarcelKaemper** [comment]
We will upload a demo version to our webserver ASAP. You can expect a demo version of the current game in a few days. I will respond to this issue with a link to the game. 
Thank you for your interest.

**Comment by MarcelKaemper** [comment]
The live demo could take some more time due to our host. Please be patient

**Comment by MarcelKaemper** [comment]
The demo version is ready! Tell us what you think. https://marcelkaemper.deinsh.eu

**Comment by wumix** [comment]
Hey ich hatte leider keine Zeit mir diese Demo anzuschauen würdest du diese wieder online stellen?
